/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconAdd: typeof import('./src/components/icon/Add.vue')['default']
    IconArrowDown: typeof import('./src/components/icon/ArrowDown.vue')['default']
    IconBackOff: typeof import('./src/components/icon/BackOff.vue')['default']
    IconBrokenLine: typeof import('./src/components/icon/BrokenLine.vue')['default']
    IconCopy: typeof import('./src/components/icon/Copy.vue')['default']
    IconDelete: typeof import('./src/components/icon/Delete.vue')['default']
    IconDrag: typeof import('./src/components/icon/Drag.vue')['default']
    IconEmpty: typeof import('./src/components/icon/Empty.vue')['default']
    IconExport: typeof import('./src/components/icon/Export.vue')['default']
    IconFoldAllNode: typeof import('./src/components/icon/FoldAllNode.vue')['default']
    IconForward: typeof import('./src/components/icon/Forward.vue')['default']
    IconMenu: typeof import('./src/components/icon/Menu.vue')['default']
    IconMinus: typeof import('./src/components/icon/Minus.vue')['default']
    IconNotice: typeof import('./src/components/icon/Notice.vue')['default']
    IconOmit: typeof import('./src/components/icon/Omit.vue')['default']
    IconOpenAllNode: typeof import('./src/components/icon/OpenAllNode.vue')['default']
    IconPlus: typeof import('./src/components/icon/Plus.vue')['default']
    IconRight: typeof import('./src/components/icon/Right.vue')['default']
    IconRightArrow: typeof import('./src/components/icon/RightArrow.vue')['default']
    IconRun: typeof import('./src/components/icon/Run.vue')['default']
    IconSelfAdaption: typeof import('./src/components/icon/SelfAdaption.vue')['default']
    IconSetting: typeof import('./src/components/icon/Setting.vue')['default']
    IconSmoothLine: typeof import('./src/components/icon/SmoothLine.vue')['default']
    IconTestRun: typeof import('./src/components/icon/TestRun.vue')['default']
    IconUserSetting: typeof import('./src/components/icon/UserSetting.vue')['default']
    IconVideo: typeof import('./src/components/icon/Video.vue')['default']
    IconWorkFlowRunResult: typeof import('./src/components/icon/WorkFlowRunResult.vue')['default']
    IconWorkFlowRunResultCLose: typeof import('./src/components/icon/WorkFlowRunResultCLose.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
